_target_: dmanus.DManus
ee_cfg:
  dynamixel:
    motor_lims:
      pos_lims:
        high:
          10: 4.85
          11: 2.90229165
          12: 4.7
          20: 3.5
          21: 2.98
          22: 4.7
          30: 4.15
          31: 3.5
          32: 5.4
          33: 5.4
        low:
          10: 2.7
          11: 2.35
          12: 3.5
          20: 1.75
          21: 1.7
          22: 3.5
          30: 2.335
          31: 1.8
          32: 3.14
          33: 2.7
      tor_lims:
        high:
          10: 500
          11: 500
          12: 500
          20: 500
          21: 500
          22: 500
          30: 500
          31: 500
          32: 500
          33: 500
        low:
          10: -200
          11: -200
          12: -200
          20: -200
          21: -200
          22: -200
          30: -200
          31: -200
          32: -200
          33: -200
    motor_params:
      baudrate: 1000000
      devicename: /dev/ttyUSB0
      motor_type: X
      protocol: 2
    active_motors: 
      - 32
      - 33
    close_engaged: false
    cmodes_set: false
    control_mode:
      10: P
      11: P
      12: P
      20: P
      21: P
      22: P
      30: P
      31: P
      32: P
      33: P
    init_torques:
      22: 50
      32: 50
    reset_pos:
      - 4.05737918 
      - 3.02040817 
      - 4.33809767 
      - 2.72741784 
      - 2.87774796 
      - 4.14174813 
      - 2.87007805 
      - 3.32106841 
      - 3.61099077 
      - 4.34883553
    shutdown_torques:
      22: 10
      32: 10
  presetup: false
